"""Add structure_file column to Syllabus

Revision ID: 0ee311a41b97
Revises: 440e41818cf2
Create Date: 2025-10-27 21:19:33.738880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee311a41b97'
down_revision = '440e41818cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabus', schema=None) as batch_op:
        batch_op.drop_column('structure_file')

    # ### end Alembic commands ###
