"""test

Revision ID: 440e41818cf2
Revises: 
Create Date: 2025-10-27 21:18:42.634627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '440e41818cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabus', schema=None) as batch_op:
        batch_op.drop_column('structure_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_file', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))

    # ### end Alembic commands ###
